### ISSUE TITLE
Selecting "Continue" from in-game menu generates additional button press in game

### ISSUE THREAD

**Issue by laesetuc** [spruceUI/spruceOS#1]
Basically when I access the in-game menu, and then select Continue to exit the menu, it generates an additional button press about 50% of the time.

To reproduce:
1. Gambatte core
2. Play "Picross 2" or "Mario's Picross"
3. Press "Menu" button
4. Select "Continue" and press "A" button
5. About 50% of the time it will generate an additional "A" button press when resuming the game

I think this is limited to the Gambatte core, and I have a few other games such as Catrap and they show the same behaviour.
However cores such as MGBA and SNES (mednafen_supafaust) don't have this problem.

It is a nuisance especially with puzzle games where clicking on the wrong thing can lose you points.

**Comment by spruceUI** [comment]
Hey thanks for pointing this out! i did some testing and it seems like i can reliably do it either way depending on how how/long i press A. I believe this is tied up with MainOS so i doubt ill be able to find a fix for it unfortunately.

**Comment by laesetuc** [comment]
Ah thanks for looking into it!  It's a minor nuisance but I can live with it I suppose!
