### ISSUE TITLE
The volume value can only been stored in the game mode.

### ISSUE THREAD

**Issue by KyleBing** [spruceUI/spruceOS#106]
Changing volume in the main menu will not be stored after reboot a30.
Volume value can only been change and stored in game mode.

For example, initial volume value is 10, If you change volume to 20 in main menu, enter a game then leave it, the volume will still be 10. But if you change it in the game mode, chaging it to 15 for example, the value 15 will be stored after you leave the game.

- SpruceOS Verison: `v2.3`
- Devce: `MiyooA30`

**Comment by ryanmsartor** [comment]
@FragBait79 has a fix for this incoming for the next version of spruce!
