### ISSUE TITLE
set uae4arm default for Amiga, add Atari ST folder for games

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#107]
As the title says the uae4arm core is way faster than PUAE for Amiga games.  It runs most games full speed even on my raspberry pi 2w, even heavy copper use ones like "Lionheart". Also add a folder for Atari ST games (Hatari default), i haven't seen one, there is an ATARI which i guess is for 2600

**Comment by cobaltgit** [comment]
This pull request should do the job. Yes, the ATARI folder is for 2600 games.

**Comment by metallic77** [comment]
That was quick, thanks. Lakka that is linux and retroarch works wonders on pi 2w with uae4arm. Haven't tested this much but it should perform the same.

**Comment by cobaltgit** [comment]
#108 merged

**Comment by cobaltgit** [comment]
I wonder why uae4arm is always running at half speed without fastforward...

**Comment by metallic77** [comment]
I noticed the raspberry pi lakka version has an option for fast copper too, that's missing from this version. Uae4arm should be full speed normally.

**Comment by cobaltgit** [comment]
Hm, I've just compiled uae4arm libretro from source and it has the option

**Comment by metallic77** [comment]
Good, how does it perform?

**Comment by cobaltgit** [comment]
A bit better in fastforward mode (i compiled with cortex-a7 tune) but more or less the same, I can't nail down why it's running at half speed without fastforward

**Comment by cobaltgit** [comment]
Atari ST seems to boot into the Hatari menu for some reason

**Comment by metallic77** [comment]
It works if launched from retroarch but not launching games from main menu, i transferred your changes to sd card.

**Comment by metallic77** [comment]
> A bit better in fastforward mode (i compiled with cortex-a7 tune) but more or less the same, I can't nail down why it's running at half speed without fastforward

I have some clues. First of all core runs at 60 fps meaning NTSC, while most amiga games made in pal 50hz. Second if you disable audio sync in settings-audio then bang, solid 60 fps at all times. There is a) format is wrong, should be pal and b) audio sync

**Comment by cobaltgit** [comment]
Thanks for the tip...pushed the optimised core and config override to the devel branch ([1e8f1b9](https://github.com/spruceUI/spruceOS/commit/1e8f1b965954ec33e15f0d8a2d08c9adb24e464b))

**Comment by metallic77** [comment]
> Thanks for the tip...pushed the optimised core and config override to the devel branch ([1e8f1b9](https://github.com/spruceUI/spruceOS/commit/1e8f1b965954ec33e15f0d8a2d08c9adb24e464b))

Another tip, if you enable "sync to exact content framerate" in video-synchronization it goes back to 50hz. Did some testing, performance is fantastic. It runs Risky Woods really well, while more powerful SoC can't do in puae. Still audio is a bit messed up

**Comment by metallic77** [comment]
I think i sorted the uae4arm audio issue.

1. Audio sync off. 
2. Audio driver alsa. Seems to work properly on this core?
3. Video->synchronization, sync to exact content frame rate on. Back to 50hz.

Built-in file manager helped a lot to tweak files and test on the fly

Now on proper 50hz and perfect audio.

Your Atari ST setup wasn't launching because there was no default.opt and system.opt in Emu/ATARIST, when i copied them and changed core to hatari in those files it launches games normally from the list.

**Comment by cobaltgit** [comment]
Alright, I'll update that. Thank you

**Comment by cobaltgit** [comment]
Seems you're on 2.3.0, whereas in Development (3.0.0) the location of the emu opts has changed. On Development the emu opts are in `Emu/.emu_setup/defaults`, it launches into the Hatari menu for some reason instead of the game, which I want to fix

**Comment by metallic77** [comment]
Yeah i am testing on version 2.3, it works there now. There is a new hatari core too in the works, you could try to compile it and see if it runs any better. I tested on my Linux and works way better than the old retroarch core.

https://github.com/bbbradsmith/hatariB
