### ISSUE TITLE
Issue: Quick Menu puts Saves and Save States in content folder

### ISSUE THREAD

**Issue by laesetuc** [spruceUI/spruceOS#11]
I have noticed that there save states are being saved inside the Roms folder instead of the States folder.

For example with Castlevania - Symphony of the Night on Playstation using the pcsx_rearmed core, this is what I see in the various folders:

### Roms
**/Roms/PS/.pcsx_rearmed_libretro/Castlevaina - Symphony of the Night.0.state
/Roms/PS/.pcsx_rearmed_libretro/Castlevaina - Symphony of the Night.0.png**
/Roms/PS/Castlevania - Symphony of the Night.chd

### Saves
/Saves/PCSX-ReARMed/Castlevania - Symphony of the Night.srm

### States
/Saves/PCSX-ReARMed/Castlevania - Symphony of the Night.state.auto

I think the state and png files should be in the States folder...

**Comment by XanXic** [comment]
Go to Retroarch and under _Settings_ > _Saving_ make sure the setting _Write Saves to Content Directory_ and _Write Save States to Content Directory_ are turned **Off**. Spruce doesn't use this option by default so something must've happened to turn it on. That's about the only way RA would be saving them next to the roms.

**Comment by laesetuc** [comment]
Hi XanXic thanks for your reply. Both those options are turned off for me.
For clarity, it seems auto-saves (state.auto) taken by retroarch go to the /Saves/ folder, but any done manually by Spruce using the in-game menu (state.0, state.1 etc.), seems to go to the /Roms/ folder.

Could you double check on your device to see if this is happening as well?

There's also some discussion here:
https://www.reddit.com/r/miyooa30/comments/1fd3ohr/save_states_location/

**Comment by XanXic** [comment]
Ah okay, good to know. Yeah that seems to be more specific and an issue. We'll look into it.

**Comment by laesetuc** [comment]
Thank you!

**Comment by NerfHerder421** [comment]
I think this behavior may be hardcoded into the ra32.miyoo binary. The TrimUI Smart Pro has the same behavior with its custom build of RetroArch

**Comment by XanXic** [comment]
We are going to close this and call it a "known limitation." There's the possibility of us editing the ra32 binary but it's a low priority for us.
