### ISSUE TITLE
RetroAchievements in PPSSPP?

### ISSUE THREAD

**Issue by robonxt-ai** [spruceUI/spruceOS#124]
I was able to connect RetroAchievements in retroarch and it's working great, however once I'm in PPSSPP, I cannot add RetroAchievements because it requires a keyboard. Is there an option I missed, or some process I need to do to enable it?

**Comment by Sundownersport** [comment]
theres some weird thing with this, ppsspp is closed source and we cant really change much about it. give me a few ill try to hunt down the workaround.

**Comment by Sundownersport** [comment]
i believe this talks about it

https://www.reddit.com/r/RetroAchievements/comments/16lil4u/comment/k6tnv7c/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by robonxt-ai** [comment]
The thing is I cannot enter the password at all since PPSSPP believes we have a keyboard connected, which we don't. The virtual keyboard, if there is one, isn't showing up either, so I cannot type it in anyways. I am, however able to enter in my username, as that is stored as plaintext in the .ini/config file

**Comment by Sundownersport** [comment]
Yes this is a known bug with ppsspp

you need to edit the files manually on a computer

**Comment by robonxt-ai** [comment]
Gotcha. Could there be a page (or link) in the wiki mentioning this issue and solution for future users?

**Comment by Sundownersport** [comment]
ill add it to my list of things to add

**Comment by Sundownersport** [comment]
lol it was already in the wiki!
 #5
 https://github.com/spruceUI/spruceOS/wiki/FAQ

**Comment by robonxt-ai** [comment]
Oh haha! I missed that big time.

Just an update, I have successfully gotten RA to work in PPSSPP by following the steps, will close this issue!

**Comment by Sundownersport** [comment]
great! i feel dumb too, it took me quite some time sorting through old discord messages to find the link i had already put into the wiki........
