### ISSUE TITLE
File management app doesn't work

### ISSUE THREAD

**Issue by fancypantalons** [spruceUI/spruceOS#14]
* Relatively modern Lexar 128 GB flash card
* Running Spruce V2.0
* Updated to 282 firmware

Selecting File Management from the Apps list results in the screen going blank, then "Loading", and then I'm returned to the Apps list.

I assume something is wrong in the launcher or the installation of the app.  Any chance there's a log somewhere I can explore to dig deeper into this issue?

**Comment by Sundownersport** [comment]
Follow the update procedure and reinstall 2.0.

**Comment by fancypantalons** [comment]
Sorry, meant to follow up.  Yeah, my guess is bad SD card or failed copy, as a fresh install of V2.1 worked just fine.  Apologies for the false alarm, and thank you!
