### ISSUE TITLE
Audio problems with chimerasnes SFC core

### ISSUE THREAD

**Issue by hugorosario** [spruceUI/spruceOS#140]
I have audio issues using the chimerasnes core.
Tested with both Chrono Trigger and Final Fantasy 3.
It seems to start fine and a few seconds into the game, it starts to sound like crap.

It works fine in snes9x.

I changed the core settings to match the recommendation without any effect.

Video > Threaded Video = ON (default is OFF)
Audio > Output > Audio Latency (ms) = 128 (default is 64)
Audio > Resampler > Audio Resampler = sinc (this is the default)
Audio > Resampler > Resampler Quality = Lowest (default is Lower)

**Comment by cobaltgit** [comment]
I'm willing to bet it's a core issue (it's based on snes9x 2005), I've noticed it in games such as super mario world
