### ISSUE TITLE
DraStic not using RTC by default.

### ISSUE THREAD

**Issue by Cren-Verdis** [spruceUI/spruceOS#16]
I was playing Pkmn SS/HG and noticed that the clock wasn't syncing up correctly. In a (relatively old) post it's mentioned that an options entry should be there where one could switch DraStic to use the hardware clock.

I looked for the cfg file and I had to manually edit the entry of /Emu/NDS/config/drastic.cfg
at line 25:
replace
`rtc_system_time = 0`
with
`rtc_system_time = 1`

Maybe that flag could be set by default?

**Comment by spruceUI** [comment]
changed it for the next release.
