### ISSUE TITLE
Password with special characters

### ISSUE THREAD

**Issue by farbod21** [spruceUI/spruceOS#172]
I still can't use a wifi password with special characters. I use to get around this by editing the password in the config file, but I cannot find this any longer. Can you tell me where that file is located?

**Comment by ryanmsartor** [comment]
If entering your password via the main UI's wifi menu, you can simply put a backslash `\` before your special characters - for example, one network I connect to has a `<`, so I enter it as `\<`.

You can also use the new multipass.cfg at the root of the SD card to add your network and password. Simply type your SSID and PSK into the variables contained in that file, then once you boot your A30 it will evaluate the contents, add it to your WPA supplicant config file (which stores your networks), and then delete the multipass.cfg off the root of the SD card for security's sake. If doing it this way, then you do not need to escape (most?) special characters.

**Comment by farbod21** [comment]
Perfect.  Thank you!
