### ISSUE TITLE
No Select+KEY shortcuts 

### ISSUE THREAD

**Issue by Stooovie** [spruceUI/spruceOS#174]
Hi, I updated to the 3.0.0, it works well except the Select button shortcuts. None of those does anything for me. How can I troubleshoot that? Also the "R2 for Fast forward" feature is gone. 

Thanks for any tips.

**Comment by Sundownersport** [comment]
FF should be Select+R2 to toggle on/off

**Comment by Stooovie** [comment]
Oh boy, I missed that even going twice into that menu looking for a fix. Thanks! It's a truly transformative release.

**Comment by Sundownersport** [comment]
Glad you got it sorted out!
Thanks, we really appreciate it😎
