### ISSUE TITLE
ScummVM cursor rolling up

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#180]
ScummVM core emulated mouse cursor rolling up without doing anything.

**Comment by Sundownersport** [comment]
It’s working good for me?

can you try to calibrate the stick in the main setting tab and try it again?

**Comment by metallic77** [comment]
Ok will do and report. Another question, what extension do we need for scummvm to detect "roms" in main UI? Dropped broken sword as a folder and zip but no. It plays if i start core inside retroarch, scan folder,  thenit appears in scummvm built in list.

**Comment by Sundownersport** [comment]
.scummvm

**Comment by Sundownersport** [comment]
Scummvm is so odd, it’s on my list of systems that NEEDS a proper wiki entry

**Comment by metallic77** [comment]
> .scummvm

So we need to rename .zip to .scummvm?

**Comment by Sundownersport** [comment]
Not sure hold on somewhere I have a write up on this

**Comment by Sundownersport** [comment]
https://gist.github.com/blkxltng/bc9b0397cb017fb547899247298e1f24

**Comment by metallic77** [comment]
Seems the rolling cursor is fixed after calibrating, but emu_fresh app missing from spruce os 3.0? So still the "roms" not appearing, but if i launch the .scummvm file inside retroarch it directly launches the game.

**Comment by Sundownersport** [comment]
I have an idea…. Can you message me on discord?
