### ISSUE TITLE
Default Core association for arcade games

### ISSUE THREAD

**Issue by elfiestador** [spruceUI/spruceOS#185]
Hello dev team,
Just updated to v3.0, what a good work !
Unfortunately, have an issue with Arcade playlist: On previous version of Spruce, arcade games were associated with Mame2003 core.
On 3.0, arcade playlist is associated with FBNeo causing the games to crash at launch (missing files).
Is there a way to setup default core association ?
Thank you !

**Comment by ryanmsartor** [comment]
Hey - in your Arcade games list, press the X button to bring up a menu. There, you can change the core to default to MAME2003plus for the entire folder.

As an alternative, you can also just move the contents of your ARCADE Roms folder (which is set up as noted above, to allow for variable core selection) into the MAME2003PLUS Roms folder (which always uses that core).

**Comment by elfiestador** [comment]
Thank you for your quick replies, it works again now !
