### ISSUE TITLE
3.0.1 Sonic Mania Doesn't launch from menu, but does launch from file explorer

### ISSUE THREAD

**Issue by Cranmoot** [spruceUI/spruceOS#188]
Just bringing to your attention.  Sonic Mania doesn't launch from Ports Menu, but it does run in file browser executing 'sonicmania.launch'

**Comment by Sundownersport** [comment]
Try the updated version

https://github.com/spruceUI/Ports-and-Free-Games/releases/tag/sonic-mania-fix

**Comment by Cranmoot** [comment]
Confirmed fix! right on!
