### ISSUE TITLE
Non stop audible whine from speaker

### ISSUE THREAD

**Issue by tdavetech** [spruceUI/spruceOS#189]
Hello, I get speaker whining on a brand new unit. it is there even with the sound turned all the way down. Is there a fix for this? Or did I get a dud? Running Spruce 3.0.1

**Comment by cobaltgit** [comment]
That's a hardware thing, completely normal

**Comment by Sundownersport** [comment]
As Cobalt said, Unfortunately this is just a fact of life with the A30. They are inexpensive handhelds and their hardware kind of shows it.
