### ISSUE TITLE
Miyoo A30 WiFi stuck

### ISSUE THREAD

**Issue by ANhan88** [spruceUI/spruceOS#19]
The wifi hasn't worked since I received my unit, I'm hoping a fresh flash will fix it.

**Comment by spruceUI** [comment]
This is an A30 issue, not a spruce issue. Please update your Firmware.

Here is a link to the wiki with instructions:

https://github.com/spruceUI/spruceOS/wiki/Updating-Firmware-and-Unbricking-an-A30
