### ISSUE TITLE
Use full path when loading rom with retroarch

### ISSUE THREAD

**Issue by surskitt** [spruceUI/spruceOS#192]
On my setup, I have disabled the "Sort saves into folders by core name" setting and enabled "Sort saves into folders by content directory", to match the settings on my other devices and allow my A30 to load saves from the directories synced by syncthing.

This works mostly, but sometimes the root save directory (/mnt/SDCARD/Saves/saves) is used instead. I figured out this is due to the file path being loaded by retroarch sometimes including an extra dot in the path, so instead of:

`/mnt/SDCARD/Roms/gba/game.zip`

it ends up being

`/mnt/SDCARD/Roms/gba/./game.zip`

and it seems to be using the dot as the content directory instead of `gba`.

(more acurately, it's something like `/mnt/SDCARD/Emu/GBA/../../Roms/gba/./game.zip`, but it's the final parts of the path that are relevant).

On my local install I've changed the following code in `Emu/.emu_setup/standard_launch.sh` from:

```
HOME="$RA_DIR/" "$RA_DIR/$RA_BIN" -v -L "$RA_DIR/.retroarch/cores/${CORE}_libretro.so" "$1"
```

to

```
ROM_FILE="$(readlink -f "${1}")"
HOME="$RA_DIR/" "$RA_DIR/$RA_BIN" -v -L "$RA_DIR/.retroarch/cores/${CORE}_libretro.so" "${ROM_FILE}"
```

this works but maybe something a little more sophisticated would be better if this were to be added.

**Comment by BaseInfinity** [comment]
Sounds like a bug with how we call the script in some places since `$1` is an argument passed along with the script.

Sanitizing the path here works but we should also see how this script is called and sanitize it higher up if possible

**Comment by surskitt** [comment]
This should be fixed with the referenced commit and today's new release.
