### ISSUE TITLE
some psp games fail to detect memory stick (for ingame saves)

### ISSUE THREAD

**Issue by depauperado** [spruceUI/spruceOS#197]
On spruce 3.0.0 and 3.0.1 there are some games that show error when trying to save/load ingames saves (it seems that save states work fine).

The games that i detected with this problem are:

- final fantasy iv the complete collection (when trying to load/save, it gets locked on a screen error)
- N+ (inform that there isn't a memory stick and tells you that you won't be able to save anything)
- both yarudora english patched games (they show some error in japanese, lol)

Games that i tested that DON'T have this problem:

- Tetris
- Pacman championship edition
- Legend of heroes: A tear of vermillion

![photo_2024-11-19_21-45-46](https://github.com/user-attachments/assets/8d8f7600-dced-4efd-8b3c-770ee2ab5d4d)
![photo_2024-11-19_21-45-39](https://github.com/user-attachments/assets/e8ac9e03-a8da-48f8-8924-b78b4c9c3ea1)

**Comment by depauperado** [comment]
I made the change on my ppsspp.ini file and the games with this problem are working fine now, also the games that didn't have this problem are also working fine.

should i close this issue? or wait for the next release?

![photo_2024-11-25_10-49-46](https://github.com/user-attachments/assets/45f1cced-07b1-47e8-8c1f-ae23917faa96)

**Comment by Sundownersport** [comment]
Leave it open. We close issues with “fix incoming” at release

**Comment by Luke-smith-94** [comment]
This also affects all pokemon games.... waiting for a fix as this is stopping me from using spruce

**Comment by Sundownersport** [comment]
What Pokémon games are you playing on psp? I didn’t think there are any
