### ISSUE TITLE
Enable SFTP server

### ISSUE THREAD

**Issue by robled** [spruceUI/spruceOS#198]
Would be a nice additional way to transfer files to the A30.

```
ash: /usr/libexec/sftp-server: not found
scp: Connection closed
```

**Comment by Sundownersport** [comment]
Huh? We have file transfers via WiFi?

2 kinds of it, sort of 3 really.

can you explain what you mean a bit more please?

**Comment by ryanmsartor** [comment]
Spruce already has a number of similar protocols for file transfer: ADB push, SAMBA, HTTP, and FTP.

I’m not personally one of the network gurus on the team, but I don’t particularly see putting in the effort to add another protocol. Can you explain the use case for SFTP where the none of the others would quite do the job?

**Comment by robled** [comment]
Indeed, the web interface and SMB are available and they work fine.  

In my case I'm often editing config files and managing files via SSH, and it would be convenient to use that same interface to transfer files and stay within my terminal as opposed to switching to another program.

Not a big deal, just a personal preference.

**Comment by ryanmsartor** [comment]
Tagging @FragBait79 on here as he is the one who got SSH and FTP running for us in the first place

**Comment by Sundownersport** [comment]
Can I ask what you why you find yourself editing config files often?

is there something else we should be looking at?

**Comment by robled** [comment]
I like to tinker with the retroarch configs and gamelist files without having to go through the menus.  Certainly not a common use case.  🤷
