### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by Steven1977uk2002** [spruceUI/spruceOS#199]
Are there any limitations on larger sd cards? I've followed the guide but when I boot up for the first time on a sandisk 1.5TB card im stuck on a loading screen and it doesn't do anything alough the blue light does flicker. Everything works on 1TB card but the new larger card I can't get past this screen.

**Comment by Sundownersport** [comment]
You are finding out for us lol.

there are definitely reports of 256 and above cards having hit or miss success. Largest any team member has tested was 512
