### ISSUE TITLE
OpenBOR has wrong image path defined

### ISSUE THREAD

**Issue by Ythan** [spruceUI/spruceOS#20]
Very minor issue, but OpenBOR is using the wrong path for game images.

In Emu\OPENBOR\config_hidden.json, this line:
`"imgpath":	"../../Imgs/OpenBOR",`

should be:
`"imgpath":	"../../Roms/OpenBOR/Imgs",`

**Comment by spruceUI** [comment]
cool! ill update that

Thanks!
