### ISSUE TITLE
What about Redream?

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#200]
Isn't porting this Dreamcast emulator possible? 
I see there are builds for linux, at least x86_64?
I mean maybe it could be done on arm too?
It looks like it runs better than Flycast at least on android phones that i tested it. Would most probably boost DC performance a lot. Just a suggestion.

**Comment by cobaltgit** [comment]
Redream is a proprietary emulator, so it running on an arm 32bit host would be little more than a pipe dream.

**Comment by ryanmsartor** [comment]
@cobaltgit well the upscaling thing is a little beside the point considering we’d never need higher than original resolution.😅

I do see there’s a raspberry pi version but not sure if it’s the correct architecture still. The A30 runs on armhf and is 32-bit only. We can look into it at the very least

**Comment by cobaltgit** [comment]
> I do see there’s a raspberry pi version but not sure if it’s the correct architecture still. The A30 runs on armhf and is 32-bit only. We can look into it at the very least

IIRC the raspberry pi version is arm64-only

**Comment by metallic77** [comment]
If it works it's worth it. Talking about monstrous performance at least on Android. And i did comparisons, flycast runs at half frame rate at best

**Comment by cobaltgit** [comment]
```
root@2b18058c9066:~# ldd redream.elf
./redream.elf: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./redream.elf)
./redream.elf: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./redream.elf)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x3f7d0000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x3f7bd000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x3f7a7000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x3f657000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x3f5df000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x3f5b4000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x3f4c8000)
        /lib/ld-linux-armhf.so.3 (0x40000000)
```
Can confirm our glibc is outdated

**Comment by cobaltgit** [comment]
They haven't had a stable release in 5 years, last devel release was 3 months ago

**Comment by metallic77** [comment]
Well yes. Performance looks absolutely incredible so it's a pity unless there is a workaround 

https://m.youtube.com/watch?v=nixMByTYpus&t=206s&pp=2AHOAZACAQ%3D%3D

**Comment by cobaltgit** [comment]
The rpi4 has 4x cortex a72 cores clocked at up to 1.5ghz afaik (can be overclocked to ~1.8ghz which is the case with the rpi400 out of the box), our little A30 has 4 cortex a7 cores that can barely scratch 1.5ghz, not even all of them can reach that frequency and maintain stability so assume 1.3ghz is the max stable frequency for all a30s. 

The huge gap in CPU power more than likely explains the performance gap, my TRIMUI Smart Pro with 4x a53 cores at 1.8ghz can run ikaruga at full speed with the flycast standalone emulator so yeah

**Comment by metallic77** [comment]
I am almost sure it will boost performance compared to flycast. I was running them both on a Snapdragon 650 phone and there is a visible difference, redream runs better. Isn't there any way to provide a more updated libc and guide the executable to use it like LD_LIBRARY_PATH? Not an expert on the matter just asking

**Comment by ryanmsartor** [comment]
Unfortunately not - GLIBC is one of the few dependencies we can’t get around by putting in LD_LIBRARY_PATH. It’s too deeply embedded in the OS.

 But if they can help with an armhf build depending on glibc2.23 or earlier, I’d love to test it out

**Comment by cobaltgit** [comment]
> But if they can help with an armhf build depending on glibc2.23 or earlier, I’d love to test it out

Very, very wishful thinking

**Comment by metallic77** [comment]
Just to get an idea how important is software quality-drivers-optimisation etc, tried retroarch flycast on an htc one m7 that has quad core arm A15 at 1.8ghz and adreno gpu and won't even display anything and stutters more than a miyoo a30. N64 RA cores won't start anything too, mupen64 standalone performs about the same with miyoo a30 if not worse. Actually in the end, a30 performance and software quality isn't bad at all.
