### ISSUE TITLE
Should replace km_flycast_extreme with flycast as default.

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#201]
The latter works equally if not better and avoids errors like Resident Evil 3 Nemesis graphics glitch that renders it unplayable on the former. Probably many errors in other games too. Now RE3 is perfectly playable with flycast. No errors and almost full speed.

**Comment by ryanmsartor** [comment]
That’s not been my experience personally - the xtreme version does cause some graphical issues in places, but for me at least, a lot more games are playable at full speed, or close to it, with the xtreme core. I’ll try asking around to see how that compares with others’ experiences.

**Comment by metallic77** [comment]
Ikaruga and RE3 work almost perfectly at 640x480. Much better overall experience than previously and same if not better frame rate. Graphics glitches gone and RE3 is playable again.

**Comment by metallic77** [comment]
> That’s not been my experience personally - the xtreme version does cause some graphical issues in places, but for me at least, a lot more games are playable at full speed, or close to it, with the xtreme core. I’ll try asking around to see how that compares with others’ experiences.

It could be that some games run better at 320x240 but introducing graphics glitches that render games unplayable is a deal breaker. Should be a 2nd option imo. I much prefer running Ikaruga and RE3 in that quality tbh
