### ISSUE TITLE
Possible to add xrandr custom 50hz resolution?

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#209]
Most Chinese monitors/screens I've seen do support 50/60hz. That would be a feature set the handheld apart from anything else around, running pal games smooth like C64/Amiga etc. I guess xrandr isn't even in miyoo firmware but maybe there could be a way around.

**Comment by cobaltgit** [comment]
We'd need the entire X Window System for that iirc..

**Comment by metallic77** [comment]
Well that's too bad then
