### ISSUE TITLE
PCSX game save not detected 

### ISSUE THREAD

**Issue by Stooovie** [spruceUI/spruceOS#210]
PSX game save (srm) not loading 

Hi, I have a savegame (.srm) from pcsx_rearmed (RetroArch on iPad) that I put onto the Miyoo (Spruce 3.0) into /Saves/saves/PCSX-ReArmed but the Miyoo doesn't see it. The game says "There is no Suikoden 2 save data". 

Its the same emulator and the filenames match. 

Any tips?

**Comment by cobaltgit** [comment]
Must be because the save file format isn't compatible between the two cores? Hmm

**Comment by BaseInfinity** [comment]
Do you have "Save by Core Name" enabled in RetoArch on the A30?

**Comment by Stooovie** [comment]
I can't really tell, that one option is bugged, look:

https://github.com/user-attachments/assets/a0259459-bfbd-4c66-9dcb-4313b393d8fc

**Comment by BaseInfinity** [comment]
it's not bugged persay, the text just wont fit. 

If you mash "right" while having the option highlighted, this will set the option to "ON" so RA looks for game saves in the <path/to/folder/saves/core-name/romname>

**Comment by Stooovie** [comment]
Right, thanks. The savegame does appear in the same place as the one I want to transfer from Retroarch on iPad, but the .srm from RA iPad is 4 kB, and the .srm from A30 is 131 kB. What gives? In RA options I see compression for States but not for Saves.

Thanks for your time!
