### ISSUE TITLE
nKaruga port? (suggestion)

### ISSUE THREAD

**Issue by metallic77** [spruceUI/spruceOS#212]
There is this excellent little ikaruga clone here

https://github.com/gameblabla/nKaruga

that compiles and runs like a charm on linux x86_64, but fails on my crappy armhf docker image (probably missing some dev libraries), perhaps someone with a better cross compile enviroment could try to do it.  This looks like a light little game that would be doable on the A30.

**Comment by cobaltgit** [comment]
Oo, I might try compile this later today

**Comment by cobaltgit** [comment]
```
/mnt/SDCARD/Roms/PORTS/nkaruga # LD_LIBRARY_PATH="/mnt/SDCARD/miyoo/lib:$LD_LIBRARY_PATH" ./nKaruga.elf
./nKaruga.elf: symbol lookup error: ./nKaruga.elf: undefined symbol: Mix_PlayChannel
```

**Comment by metallic77** [comment]
Something wrong with libsdl2-mixer linking?

**Comment by cobaltgit** [comment]
Had to change around the makefile a bit, here's the linker flags output at the end of the make job:
```
arm-a30-linux-gnueabihf-g++ src/n2DLib.o src/BossEnemy.o src/Joint.o src/DrawingCandidate.o src/DestroyedEnemies.o src/Entity.o src/ChainNotif.o src/Particles.o src/Bullet.o src/Laser.o src/main.o src/utils.o src/Player.o src/SoundHandle.o src/BackgroundScroller.o src/PowerFragment.o src/ExplosionAnim.o src/BulletArray.o src/EnemiesArray.o src/ExplosionEffect.o src/DrawingCandidates.o src/Menu.o src/Homing.o src/buildGameLUTs.o src/Enemy.o src/Level.o -o nKaruga.elf -Ofast -fdata-sections -ffunction-sections -I/opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/include/ `/opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/bin/sdl2-config --cflags` -DHOMEDIR -std=c++11 -fno-exceptions -fno-rtti -L/opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/lib -lSDL2 -lSDL2_mixer -lm -Wl,--as-needed,--gc-sections -flto -s -static-libstdc++
```

**Comment by metallic77** [comment]
Probably doable but needs someone that can do the trick, also me not an expert only basic knowledge

**Comment by metallic77** [comment]
A

**Comment by cobaltgit** [comment]
```
CROSS_COMPILE = arm-a30-linux-gnueabihf
CC = $(CROSS_COMPILE)-gcc
CXX = $(CROSS_COMPILE)-g++
LD = $(CROSS_COMPILE)-g++
SDL_CONFIG = /opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/bin/sdl2-config
CFLAGS = -Ofast -fdata-sections -ffunction-sections -I/opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/include/ `$(SDL_CONFIG) --cflags` -DHOMEDIR
CXXFLAGS = $(CFLAGS) -std=c++11 -fno-exceptions -fno-rtti
LDFLAGS = -L/opt/a30/arm-a30-linux-gnueabihf/sysroot/usr/lib -lSDL2 -lSDL2_mixer
LDFLAGS += -lm -Wl,--as-needed,--gc-sections -flto -s -static-libstdc++
EXE = nKaruga
DIRECTORIES = ./src
OBJS = $(patsubst %.c, %.o, $(shell find $(DIRECTORIES) -name \*.c))
OBJS += $(patsubst %.cpp, %.o, $(shell find $(DIRECTORIES) -name \*.cpp))


#
all: $(EXE).elf

%.o: %.c
        @echo Compiling $<...
        @$(CC) $(CFLAGS) -c $< -o $@

%.o: %.cpp
        @echo Compiling $<...
        @$(CXX) $(CXXFLAGS) -c $< -o $@

$(EXE).elf: $(OBJS)
        +$(LD) $^ -o $@ $(CXXFLAGS) $(LDFLAGS)

.PHONY: clean
clean:
        rm -f `find . -name \*.o`
        rm -f $(EXE).elf
```
Modified makefile I used

**Comment by metallic77** [comment]
This is how they run it on portmaster if it helps somehow 

#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt

get_controls

$ESUDO chmod 666 /dev/tty1

GAMEDIR="/$directory/ports/nkaruga"

cd $GAMEDIR
$ESUDO chmod 666 /dev/uinput
$GPTOKEYB "nKaruga.elf" -c "$GAMEDIR/nkaruga.gptk" &
SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig" ./nKaruga.elf 2>&1 | tee $GAMEDIR/log.txt
$ESUDO kill -9 $(pidof gptokeyb)
$ESUDO systemctl restart oga_events &
printf "\033c" > /dev/tty1

**Comment by metallic77** [comment]
I did compile an executable in another Ubuntu 20.04 arm32 docker image and after
readelf -a -W nKaruga.elf

I got some info

Dynamic section at offset 0x1aca8 contains 33 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libSDL2-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libSDL2_mixer-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]

**Comment by cobaltgit** [comment]
Nice one, it actually works! One small problem, and this isn't the only port with it: the display is rotated 90degrees anti-clockwise, I've had this problem when trying to port some other games, namely Celeste Classic and SDLPoP. Must be to do with the SDL2 library in `miyoo/lib`, I've tried the SDL2 from the Sonic Mania port and the rotation is fixed at the expense of controls.

**Comment by metallic77** [comment]
Cool, can we push this further to make this port happen?

**Comment by cobaltgit** [comment]
I'd be more than happy to help wherever I can! If we can fix this rotation while preserving controls then this should also open the door to the other ports I mentioned earlier

**Comment by metallic77** [comment]
The most important is that it works, we can push this port further now. 

These are the commands i used in MX Linux to build docker

```
docker pull monkeyx/retro_builder:arm32
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --privileged -it --platform=linux/armhf --name builder32 monkeyx/retro_builder:arm32 bash

```

**Comment by metallic77** [comment]
Well whatever gets the job done lol. That's why better have some xenial docker image probably.

**Comment by cobaltgit** [comment]
Here's what i've ported so far, feel free to test
[A30 Rotated Ports.zip](https://github.com/user-attachments/files/17893588/A30.Rotated.Ports.zip)

**Comment by metallic77** [comment]
What i did was create a "lib" folder inside nKaruga folder then copy the libsdl2-2.0.so.0 from sonicmania, libSDL2_mixer-2.0.so.0 from miyoo/lib, libstdv++.so.6 from miyoo/lib. Then a bash script in nKaruga, declared 

#!/bin/sh
export LD_LIBRARY_PATH="/mnt/SDCARD/Roms/PORTS/nKaruga/lib:$LD_LIBRARY_PATH"
./nKaruga.elf

And it works like a dream

**Comment by cobaltgit** [comment]
Yeah it works, just tested, however it seems to re-arrange the controls, which is what breaks other ports

**Comment by metallic77** [comment]
Yes but at least this port works. If you agree I'll create a PR to add nKaruga to ports repository as it is.

**Comment by cobaltgit** [comment]
Yeah that could work. Or i could open a pr with you as co-author in the commit if you wish?

**Comment by metallic77** [comment]
Sure man, we just wanted the game to work.

**Comment by cobaltgit** [comment]
https://github.com/spruceUI/Ports-and-Free-Games/pull/5
