### ISSUE TITLE
Fullscreen by default

### ISSUE THREAD

**Issue by Glad320** [spruceUI/spruceOS#22]
I would like fullscreen for all emulators by défaut.
Now I need to go to retroarch

**Comment by spruceUI** [comment]
I am confused. What do you mean?

**Comment by Glad320** [comment]
Gb, gbc, gba are not full screen. You have to enter the retroarch options to have a full screen. The screen is already small, removing the top two lines is painful. Same for n64

Thank you for your works

**Comment by Sundownersport** [comment]
I’ll take a look at those thanks!

**Comment by Sundownersport** [comment]
We aim for a better experience and so we believe that the majority of users will prefer the correct aspect ratio for these systems so we will not change it.
Thank you for reaching out,
Happy Gaming……….
