### ISSUE TITLE
When adjusting brightness with hotkey screen jumps brightness levels

### ISSUE THREAD

**Issue by krayhons** [spruceUI/spruceOS#231]
Brightness seems to flicker and move in double-steps when using start+R1/start+R2 hotkeys while in apps or retroarch.  Does not exhibit behavior in stock menu areas.  Behavior began in 3.0.1.  See attached video first showing normal behavior and then altered behavior in game.

https://github.com/user-attachments/assets/f98e330a-3d7d-43d7-99f9-4dcc910cff3d

**Comment by FragBait79** [comment]
This has been fixed in latest release.
