### ISSUE TITLE
spruce/test files merged + windows defender detects virus in spruceV3.1.0.7z

### ISSUE THREAD

**Issue by Gerard-Szulc** [spruceUI/spruceOS#233]
Same as a title says. 
1) I was trying to look at changes on your merge request but it was quickly merged. You merged some test files in spruce directory.

2) Windows defender detects virus in spruceV3.1.0.7z  
![image](https://github.com/user-attachments/assets/11b5cccc-dc5e-4842-ba92-9b543c3633ed)

**Comment by cobaltgit** [comment]
False positive

**Comment by Gerard-Szulc** [comment]
yup, i assume it is, just reporting, regular .zip is ok

**Comment by cobaltgit** [comment]
Hm, my windows defender didn't pick it up

**Comment by XanXic** [comment]
I'll add my defender check also cleared the 7z. I can't read, I'm assuming, Polish. Was there a specific file within the 7z your scan flagged? Or did it just flag the whole 7z?

**Comment by Gerard-Szulc** [comment]
english version 
![image](https://github.com/user-attachments/assets/87147df4-4faa-4a64-9a7f-745f4b359868)

**Comment by Gerard-Szulc** [comment]
maybe its due to new updater stuff which can download updates App/-OTA/downloader.sh ?
