### ISSUE TITLE
[Request] Please bring back the USB File Transfer feature

### ISSUE THREAD

**Issue by VampireODBC** [spruceUI/spruceOS#236]
Hi there, I've just installed Spruce on my newly bough A30. I could not find the way to transfer files (ROM, data,...) via USB connection like before. I tried searching in your Wiki, but it seems to not have my answer. Can you consider bringing the feature back? I don't want to remove and insert my SD cards frequently everytime I need to transfer my files. 
Thank you for reading this. Have a good day. And thanks for the awesome OS!

**Comment by cobaltgit** [comment]
IIRC USB file transfer on miyoo/trimui devices is known to cause sd card corruption, there are alternatives in the meantime (such as samba shares and sftpgo for network file transfer)

**Comment by VampireODBC** [comment]
> IIRC USB file transfer on miyoo/trimui devices is known to cause sd card corruption, there are alternatives in the meantime (such as samba shares and sftpgo for network file transfer)

Oh thanks for the quick reply. I'm trying to make a transfer with Wifi Transfer, but I could not make it work yet. Do you have any manual or some tutorials on how to do it :D?

**Comment by cobaltgit** [comment]
You have to enable it in advanced settings > network

**Comment by VampireODBC** [comment]
> You have to enable it in advanced settings > network

I've turned Samba & Wifi Transfer to enabled. What do I do next?

**Comment by cobaltgit** [comment]
Go to the IP of your a30 and the port that displays under wifi file transfer in a browser and log in. spruce + happygaming are user + password

**Comment by 369px** [comment]
> > You have to enable it in advanced settings > network
> 
> 
> 
> I've turned Samba & Wifi Transfer to enabled. What do I do next?

This device can only connect to 3ghz wifi, you probably have 5ghz so even if it's connecting to it, it doesn't work.

Try connecting the a30 to a mobile hotspot. Wifi file transfer app will work fine like this!

**Comment by VampireODBC** [comment]
Oh boys, you guys are incredible. Silly me when used the wrong port 8888. It works now thanks to you guys.
