### ISSUE TITLE
3.1.0 .zip file missing .config folder

### ISSUE THREAD

**Issue by nickgarvey** [spruceUI/spruceOS#237]
I am doing a fresh install of 3.1.0 and I see mention in the installation instructions that the .config folder is necessary. I don't see that folder in 3.1.0, but I do I see it in 3.0.1. Was it accidentally omitted?

**Comment by Sundownersport** [comment]
No it’s just the wiki being out of date sorry. Once you install spruce it’ll be there.

.config is only used for ppsspp 

.tmp update is the super important one.
