### ISSUE TITLE
Please create page with hotkeys in wiki

### ISSUE THREAD

**Issue by oldOwlUA** [spruceUI/spruceOS#238]
Please create page with hotkeys in wiki

**Comment by Sundownersport** [comment]
This information an be found on the main GH readme

https://github.com/spruceUI/spruceOS#retroarch

**Comment by ItsNoted** [comment]
Didn't want to make a new issue so thought I would ask here since someone asked about hotkeys. I was wondering why there is no default rewind mapping? I cant save a config in game because overrides are enabled. How would I be able to save a mapped rewind key otherwise?

Thank you!

**Comment by Sundownersport** [comment]
You can save a per game, per core or per directory override to enable rewind hotkeys.

**Comment by XanXic** [comment]
Just to add, we don't enable rewind by default since there is a measurable affect on performance. Since it's essentially creating a save state every second or so while you play it's something we rather people setup for themselves.

**Comment by djaysan** [comment]
i created a boot screen from the hotkey image in the repo description. just drag and drop it out of the folder to replace the existing bmp and run the app: https://github.com/djaysan/Spruce-RA-shortcuts-boot-logo

**Comment by djaysan** [comment]
> Please create page with hotkeys in wiki

even better as a boot logo / screen: https://github.com/djaysan/Spruce-RA-shortcuts-boot-logo

**Comment by Sundownersport** [comment]
Great! ill give it a test right now and will add it to the next release

**Comment by djaysan** [comment]
> Great! ill give it a test right now and will add it to the next release

Awesome thanks! I will probably redesign it soon in black and white lines to match better with other colors.
You are the man himself!
I'm currently busy tweaking the stock os for the Trimui Brick.
So far I gathered extra cores and configurations scattered on github/reddit, added new emulator icons, BG, bootlogo & completed the look with a new black theme: https://github.com/djaysan/Better-Stock

As soon as I'm done, I will go back to working on a theme for Spruce! Love the work you did so far! just add an easy netplay and it surpasses Onion to me :)

Cheers!

**Comment by Sundownersport** [comment]
@djaysan 3.3.0 is live and we included the bmp for bootlogo

**Comment by djaysan** [comment]
> [@djaysan](https://github.com/djaysan) 3.3.0 is live and we included the bmp for bootlogo

i reworked another version in black for the next release
