### ISSUE TITLE
Game Settings exits to Game Switcher instead of Game list

### ISSUE THREAD

**Issue by laesetuc** [spruceUI/spruceOS#244]
Steps to reproduce:

1. Advanced Settings > Game Switcher > Run GS when you exit a Game = On
2. Go to games list, highlight a game and press X to access game settings
3. Toggle a setting, for example Emu Core
4. Setting will be applied (shows loading screen) and then it will exit to the Game Switcher

In my opinion it should bring you back to the game list, not the Game Switcher.

**Comment by ryanmsartor** [comment]
Thanks for bringing this to our attention! Fix incoming in the next version of spruce.
