### ISSUE TITLE
Better theme, to include in your next release

### ISSUE THREAD

**Issue by soaremicheledavid** [spruceUI/spruceOS#25]
Made a theme for miyoo a 30, works great on spruceOS, you can add it in your next release.
[MIYOO BLCK-RED BY SMD.zip](https://github.com/user-attachments/files/16787389/MIYOO.BLCK-RED.BY.SMD.zip)

**Comment by Sundownersport** [comment]
Cool! I’ll take a look!

**Comment by tenlevels** [comment]
Create a unique theme 100% or get permission from mtaras if you are going to use things from their theme. And saying "better theme" is IMO a bit weird and pompous . Stay humble out there people...

**Comment by spruceUI** [comment]
Thank you for the submission, unfortunately this theme does not meet our requirements for inclusion in spruce.

**Comment by soaremicheledavid** [comment]
People use my themes as a base, to create thier own, dont mind that, dont care if they acknowledge it or not, there is no obligation there. The theme itself, the icons, the modifications, were made by me. There is nothing from mtaras , thats visible on the a30, only a  random preview file, if you would test it, you would see. I am one of the first testers on garlic os and onion os, also working on mu os.  You just recived a testing file, for you guys to check it out, have to change a few things. Sad to see, closed minded people on this project, wish you good luck!

**Comment by Sundownersport** [comment]
Sorry if it came off that way! I am very interested in new themes, I am just trying to be super mindful of credits/recognition.

basically I am only going to be adding themes that are complete and include readme files giving credit to sources.

please please please submit a complete theme and I will give it a more thorough look
