### ISSUE TITLE
scraper reports no active network connection if libretro thumbnails site is down

### ISSUE THREAD

**Issue by Kickbut101** [spruceUI/spruceOS#259]
As far as I can tell, thumbnails.libretro.com is not responding at the moment, making the scraping check fail even with a valid wifi connection

Starts at line 222 in \App\BoxartScraper\scraper.sh
```
# Check for Wi-Fi and active connection
wifi_enabled=$(awk '/wifi/ { gsub(/[,]/,"",$2); print $2}' "$system_config_file")
if [ "$wifi_enabled" -eq 0 ] || ! ping -c 3 thumbnails.libretro.com > /dev/null 2>&1; then
    log_message "BoxartScraper: No active network connection, exiting."
	display --icon "/mnt/SDCARD/spruce/imgs/signal.png" -t "No active network connection detected, exiting..."
    sleep 3
    exit
fi
```

Probably worth adding an additional check, or secondary URL as fallback? Or maybe as simple as just making it a "libretro.com" check instead of including the subdomain thumbnails.

**Comment by Kickbut101** [comment]
Further reading into the script, looks like we rely entirely on that site.

Maybe then instead of changing URL we just change wording of error message to say "Libretro thumbnails are not available at the moment"

**Comment by ngokevin** [comment]
That'd be nice, I was toggling Wi-Fi on and off wondering why it couldn't scrape when I was able to the day before. I assumed the site was down.

**Comment by njgreb** [comment]
With libretro still being down I started putting a new scrapper script together to pull from ScreenScrapper.fr. If there is interest I could turn it into a more full app and share it out.

**Comment by ryanmsartor** [comment]
@njgreb the interest is definitely there! One of our devs @cobaltgit has been working on the original script a little to give higher availability, but we've been wanting to add additional sources for a while now, so your script to pull from screenscraper.fr sounds great. If you do put together your own app, please feel free to open a PR to get it added into spruce; we are always open to improvements and contributions.

**Comment by njgreb** [comment]
@ryanmsartor sounds good. I have it working locally with my sd card mounted to pull images and save them properly. I'm going to clean it up a bit and will share a WIP version. Then can work on making it configurable between sources. 🤞

**Comment by njgreb** [comment]
@ryanmsartor @cobaltgit I have a test working version of an updated scrapper but have some questions. Do you prefer a new issue to track discussion, a Pull request, or some other method?

**Comment by ryanmsartor** [comment]
@njgreb a pull request would be great! We can discuss there.

**Comment by XanXic** [comment]
If you could do a PR against Development. We might hold on the PR for a bit, we are working to cut our next update in a day or so. But once it's in a PR we can look at it and that has a discussion thing that will open.

**Comment by XanXic** [comment]
Closing primary issue, Scraper got some improvements in 3.2.0. OP's proposed script is being discussed in the PR.
