### ISSUE TITLE
After resume, volume is off.

### ISSUE THREAD

**Issue by dr0id123** [spruceUI/spruceOS#26]
Using Spruce 2.1; fresh install.

After resuming (e.g., power on directly back into game), the volume is reset to off (or very low).  The existing volume level prior to going into the suspend state does not persist.

Can this be resolved via software fix?

Thanks!

**Comment by Sundownersport** [comment]
It’s a feature not a bug. It was booting back into the game at FULL volume. Mute is better.

thanks for reaching out!

**Comment by dr0id123** [comment]
Sounds like this is an "all or nothing" situation with volume (e.g., no clear way to persist the existing volume level at the time of suspend).  In that case, agreed -- better to mute.  Thanks for your feedback.

**Comment by Sundownersport** [comment]
I will get another look at this, we fixed a similar issue recently and might be able to use the same method to address this as well.
