### ISSUE TITLE
Hide RetroArch in App menu?

### ISSUE THREAD

**Issue by Raithmir** [spruceUI/spruceOS#263]
Is it possible to also hide the RetroArch app in the App menu? I'm OK if it's just by way of editing some config file.

Just trying to lock down the device a little more as it's intended for my nephew. Trying to reduce my support time if he decides to start changing advanced settings in RetroArch!

**Comment by XanXic** [comment]
Yeah go to this file on your SDCard
https://github.com/spruceUI/spruceOS/blob/main/App/RetroArch/config.json
`/mnt/SDCARD/App/RetroArch/config.json`

And change "label" to "#label" that'll hide it without breaking anything.

The good news is we are working on a "simple mode" (or kids mode) for exactly what you're describing. It's under test right now. We are hopeful to get it out in the next update within the week.
