### ISSUE TITLE
Update resets Drastic configuration files

### ISSUE THREAD

**Issue by cvlnomen** [spruceUI/spruceOS#266]
I just updated my Miyoo from version 3.0.1 to version 3.1.0 using the EZ Updater. This caused all my configuration options to be reset.
Can you please make it so that the `config/drastic.cfg` file is not be reset during updates, and possibly the `resources/settings.json` file as well?

**Comment by XanXic** [comment]
Yeah, we can add those. Seems like an oversight. It'll be in the next updates file, so unfortunately you'll loose them again updating from 3.1.0 to 3.2.0 but _then_ it'll be saved lol.

**Comment by Sundownersport** [comment]
I am going to close this issue. Beginning on the next update these changes will be seen.
