### ISSUE TITLE
pico-8 not running

### ISSUE THREAD

**Issue by acesfire7** [spruceUI/spruceOS#270]
fresh install of spruce, when i try to open any pico 8 games, it shows a loading screen for a second and then kicks me back out to the game select menu

i even tried launching from the file manager, same behavior, so its not the game files.

**Comment by ryanmsartor** [comment]
hey, do you have the Raspberry Pi versions of pico8_dyn and pico8.dat added to your `Emu/PICO8/bin` folder? It's gotta be the Raspberry Pi edition specifically.

**Comment by acesfire7** [comment]
ahh i used the wrong download, my apologies

**Comment by ryanmsartor** [comment]
All good! Let me know if that doesn't fix the problem. Happy gaming!
