### ISSUE TITLE
'Ports' game freezes the GUI when quitting - can reproduce on Spruce 2.1

### ISSUE THREAD

**Issue by Miskatonic-Student** [spruceUI/spruceOS#28]
Here's how I reproduce the freeze...
Open the game '2048' (under Games/Ports), which is just a bash shell script.
Either start a game or just go straight into the Home menu.
Save state to any slot.
Scroll down to 'Exit Game' and select it.
The GUI freezes and the only button that works is power.
Needs a complete reboot.

**Comment by spruceUI** [comment]
I have reproduced this error as described. I can however use a short hold of the power button to exit back to the game menu. No reboot required.

We will look into whatever this save-state error is and try to fix it ASAP.

For now, avoid using Save States. If it freezes as described just hold the power button for a few seconds and it will force quit and go back to the game menu.

**Comment by ryanmsartor** [comment]
I think the issue at play here is the combination of Miyoo's in-game menu, which always exposes save and load state options, with single-content cores, some of which even do not support save states at all. I have remedied this for the next release of spruce - all LibRetro-based ports such as 2048 or CaveStory will be using the "expert mode" version of RetroArch, which lacks Miyoo's custom menu, and thus utilize RetroArch itself's logic for naming, saving, and loading states, including respecting whether a given core even supports that feature.

**Comment by Sundownersport** [comment]
RA ports now have this fixed. Press Home+Start to exit the game.
