### ISSUE TITLE
[REQUEST] Ability to sort systems through Spruce.

### ISSUE THREAD

**Issue by devanteweary** [spruceUI/spruceOS#280]
Currently, you have to go into each `/Emu/<system>/` folder and edit the config file there.  
And then to sort, you have to add the desired number of spaces.

I'm requesting that making sorting systems be easier, possibly something like a `/spruce/settings/system_sort.cfg` file and then inside you can put something like...

```
system=COLECO,01
system=FDS,02
system=LYNX,03
```

or

```
COLECO=01
FDS=02
LYNX=03
```

Something like that.

Thank you!

**Comment by Sundownersport** [comment]
Unfortunately we are not interested in making such changes. We have it set up how we want already. I am glad you found a way to make these changes on your own device. 

Happy gaming!

**Comment by devanteweary** [comment]
Posting this for future reference, the official method (adding spaces) works but has unintended consequences, such as showing all those spaces under the game when you use Search. IF you have enough systems, it pushes the game name off to the side where it isn't visible. So maybe not a useful solution.

Just in case anyone comes across this!
