### ISSUE TITLE
Game stutters every couple of seconds from booting up into an autosave resume until exit back to menu

### ISSUE THREAD

**Issue by ngokevin** [spruceUI/spruceOS#285]
1. Turn off A30 while in game
2. Turn the device back on
3. Spruce boots back into the game
4. The game stutters every two seconds unless I exit back to the Spruce menu and re-enter the game, then it runs perfect, even though it's the same auto-save.

- It happens every time I turn the device on and jump back into a game (happens on both GBA and PSX games).
- My Wi-Fi is off.
- Device fully charged.

Does this happen to anyone, or anything come to mind? Anything in the boot up routine that might be hanging or not cleaned up?

**Comment by Sundownersport** [comment]
I cannot replicate this issue.

What system? If it has multiple cores, which one? What game?

**Comment by ngokevin** [comment]
FF Tactics (PSX) and Megaman Battle Network Advance (GBA).

But I will close the issue for now until I post a video to have some proof. Since this doesn't sound actionable right now.
