### ISSUE TITLE
[REQUEST] Add Mesen core for FDS/NES.

### ISSUE THREAD

**Issue by devanteweary** [spruceUI/spruceOS#287]
Normally I wouldn't really care which core is used but in this particular instance, I want to request Mesen be added and possibly default.

Reason being that it's the only core that supports auto-change disk in FDS games.  
This means I can hand my friends the system or even possibly gift them an A30 (which I plan this Christmas) and not have to worry about them knowing how eject/insert disks works.

Thank you!

**Comment by ryanmsartor** [comment]
Hey Devante, we can look into it for a future version of spruce, but I wouldn’t hold my breath. From my understanding, Mesen emphasizes accuracy over speed, so I’m not sure our wimpy little A30s will be able to run it at full speed. Still, thanks for the request, I’ll see if there’s anything we can do.

**Comment by devanteweary** [comment]
Well hold up a minute, let's not call 'em wimpy!  
I've been playing PSP Dissidia 012 with no lag at all haha

**Comment by ryanmsartor** [comment]
Hey again - I did some testing with the Mesen core on the A30, and unfortunately can only manage to get it to about 66% speed. Looks like it's not gonna be possible on this hardware without someone way smarter than me doing some intense optimization on the core. For now, the performance of this core does not meet our expectations for NES emulation in spruce.

**Comment by devanteweary** [comment]
Thank you for checking on it!! Means a lot.
