### ISSUE TITLE
System icons missing in 'Games' menu unless highlighted

### ISSUE THREAD

**Issue by Miskatonic-Student** [spruceUI/spruceOS#29]
Using any theme (tested with a few, including default), some of the icons don't show up until the system is highlighted. Specifically:

1986|7800
1995|32X
2015|PICO

On mine, the ones that display without being highlighted are:
GBA
GBC
Genesis
NES
PORTS
PS2

**Comment by spruceUI** [comment]
This is an issue with your Theme. You are not using a Theme that is fully compatible with or supported by spruce.

**Comment by spruceUI** [comment]
After further review, this user is not using spruce, they are using RA30
https://github.com/jimgraygit/ra30
