### ISSUE TITLE
How to enable Retroachievements?

### ISSUE THREAD

**Issue by milnak** [spruceUI/spruceOS#294]
Home page reads:

"Network services: **Retroachievments**, RTC sync via WiFi, SSH/SFTP, Syncthing, Samba and HTTP file transfer."

But I can't figure out how to enable and configure Retro Achievements -- am I missing the obvious?

**Comment by milnak** [comment]
I looked at the source.  It seems that the [RAC check](https://github.com/spruceUI/spruceOS/blob/a5aeed37b344e263a27b9baebb4a090b853da8fe/Emu/.emu_setup/standard_launch.sh#L60C1-L60C2) requires retroarch.cfg to be configured but it's set to false by default: [cheevos_enable = "false"](https://github.com/spruceUI/spruceOS/blob/a5aeed37b344e263a27b9baebb4a090b853da8fe/RetroArch/retroarch.cfg#L67)


Is there no UI currently to enable retroachievements?  Do I need to manually edit `retroarch.cfg`?

**Comment by Sundownersport** [comment]
@milnak 

To enable RAC you open the RA app and select Achievements, enter your username/password and then save the Configuration file.

**Comment by milnak** [comment]
I don't recall seeing the RA app. I'll check again
