### ISSUE TITLE
2.1 Emulators/Roms not showing up?

### ISSUE THREAD

**Issue by vaqus** [spruceUI/spruceOS#30]
I followed the instructions to install v2.1 on my device. I got the boot instruction video. I ran EmuFresh. Still nothing is showing up.
I placed roms in the appropriate subfolders within the ROMS folder. I made sure emulator core files were present. Still nothing except an empty "PORTS" option.
I have NOT added any bios. Do I need to add one for every system?

**Comment by Sundownersport** [comment]
It sounds like an install issue. 
try going through the update process

**Comment by vaqus** [comment]
I have now tried updating the firmware following the instructions (format 2nd sd, unzip, c/p, plug in, power on) and the device will not power on.
I have tried with the cfw file in the folder, out of the folder, and as a disk image.
Do I need to use a program to image my flash drive with the disc image file?

**Comment by Sundownersport** [comment]
Here is the wiki page with full instructions 

https://github.com/spruceUI/spruceOS/wiki/Updating-Firmware-and-Unbricking-an-A30#updating-firmware

**Comment by vaqus** [comment]
Yes, this is the procedure I followed

**Comment by Sundownersport** [comment]
Dm me on discord, I can help you troubleshoot
