### ISSUE TITLE
SORR Ports

### ISSUE THREAD

**Issue by Squintz423** [spruceUI/spruceOS#31]
I just recently downloaded the new 2.1 version and the streets of rage remake will not load. I click it and it black screens for a second and then kicks me back to the menu. Please help.

**Comment by spruceUI** [comment]
sorry it took me so long to get back to you!

During the update you deleted the Emu folder (as you should have!) and that unfortunately got rid of important files for SORR.

Here is a link to our published Ports Pack that includes SORR. Simply extract the zip on drop the contents (Emu and Roms folders) onto the root of your SD card. 

https://github.com/spruceUI/spruceOS/releases/download/spruce2.1/SPRUCE.PORTS.v1.1.1.zip

Sonic Mania requires an additional file to run that we cannot provide you.
