### ISSUE TITLE
Pico-8 (Apps) glitchy - spruceV2.1

### ISSUE THREAD

**Issue by waeggyfr** [spruceUI/spruceOS#32]
spruceV2.1 on fresh formatted SanDisk Extreme 128GB with Rufus:

- File Management is not starting and falling back to App Folder
- Pico-8 in App Folder is showing up "could not connect to BBS" when connected to wifi and rebooted

Workaround for Pico-8:
Be connected to wifi, open Pico-8 in Apps, go to the installed games, start a game, quit this game with X button, go back in Splore Menu and press update...now it is downloading.

**Comment by waeggyfr** [comment]
File Management is working now!
Corrupted block on the SD card :( 

Pico-8 is still glitchy on the new SD card (Samsung)

**Comment by spruceUI** [comment]
did you update your firmware?

**Comment by waeggyfr** [comment]
no, this was a clean spruceV2.1  install followed by the wiki page and also with a new Samsung SD card, since the other one was currupted.

Pico-8 is showing the connection error just at the beginning, if you play / start an installed game and go back to splore, the connection to BBS is stable, even after rebooting the device.

**Comment by spruceUI** [comment]
firmware is different than spruce. WiFi is broken on the A30 untill you update the firmware. here is the link:
https://github.com/spruceUI/spruceOS/wiki/Updating-Firmware-and-Unbricking-an-A30

**Comment by waeggyfr** [comment]
Ahhh...you were right, i picked the one out of three A30 (two of them in the same color) which had no firmware update 🫣

Now everything works fine...Wifi is stable.
