### ISSUE TITLE
Start + select does not quit the games

### ISSUE THREAD

**Issue by manzaloros** [spruceUI/spruceOS#34]
- latest spruce version
- Latest Miyoo a30 firmware

pressing start+select in game does not quit the game as mentioned in the readme. Pressing select plus L1 or L2 a couple times in succession will quit the game and save the state. 

I will occasionally see this descriptive menu when pressing the combination of Select + L1 or L2, but when it appears is seemingly random:
![IMG_0470](https://github.com/user-attachments/assets/5315747a-3e85-4f43-af7e-3624a0cba1d0)

**Comment by spruceUI** [comment]
release version 2.1 and 2.2 use Hold Select (2 seconds) for this now instead.

The start+select was too tricky and finicky for a lot of people, myself included

**Comment by spruceUI** [comment]
thanks for pointing that out in the README though! i just fixed it.

**Comment by manzaloros** [comment]
> use Hold Select (2 seconds) for this now instead.

Awesome! Works like a charm. Thanks for updating the readme.
