### ISSUE TITLE
Issue with Update instructions in Wiki (for Mac)

### ISSUE THREAD

**Issue by laesetuc** [spruceUI/spruceOS#36]
Hi, regarding the update instructions here:
https://github.com/spruceUI/spruceOS/wiki/Updating-to-the-Latest-Release

5. Open File Explorer and navigate to the latest release .zip.
6. Right-click it and select "extract all".
7. Extract the .zip directly onto the microSD card.
8. When prompted, allow the new files to replace the existing ones.

I believe if you do choose "Replace" on a Mac, it will cause the Roms, Saves, and BIOS folders to be replaced with the empty Roms, Saves and BIOS folders from the zip archive.

Suggest maybe to copy all context except for the Roms, Saves and BIOS folders to the card instead.

**Comment by spruceUI** [comment]
I do not believe this to be the case.

**Comment by laesetuc** [comment]
Hello, I think the behaviour might be different on windows but on Mac if you copy over an existing folder and choose “Replace” it will overwrite it completely.
https://superuser.com/questions/117621/how-to-merge-and-not-replace-folders-when-copying-on-the-mac


On 10 Sep 2024, at 8:31 am, spruceOS ***@***.******@***.***>> wrote:



I do not believe this to be the case.

**Comment by spruceUI** [comment]
seems you are correct, sorry i doubted you! I will add a Mac specific Update instruction ASAP

Thank you for pointing this out, i never would have guessed that Mac does this.

**Comment by spruceUI** [comment]
Ok, i added Mac specific instructions. Can you please take a look at it and tell me if there are any edits or additions i should make?

**Comment by laesetuc** [comment]
Yep, looks good now, thank you!

On 10 Sep 2024, at 11:03 am, spruceOS ***@***.******@***.***>> wrote:



Ok, i added Mac specific instructions. Can you please take a look at it and tell me if there are any edits or additions i should make?
