### ISSUE TITLE
Ability to switch B&A for in menu items [Feature Request]

### ISSUE THREAD

**Issue by Zach1812** [spruceUI/spruceOS#45]
This OS is awesome. One of the only features that (personally) is missing is the ability to swap the A and B for in menu and in game menu usage. My issue is most of the games I play are playstation ones and when activating the in game menu or moving back to the main menu I press the wrong button (cancel or accept) and will either start up a new game or go in or out of the menu I was wanting.

Thanks for all your hard work!

**Comment by Sundownersport** [comment]
Thanks for reaching out, your request has us thinking of possible ways to accomplish this. At least one person on the team swaps a&b on their other devices somewhat frequently so you’re not alone!

I am going to close this issue for now but we might revisit it in the future.
