### ISSUE TITLE
Issue: Stuttering screen after waking from sleep after a day of use, shutdown doesnt fix issue persists on reboot.

### ISSUE THREAD

**Issue by JohnShatto** [spruceUI/spruceOS#48]
Not sure what is going on. I tried replacing the SD card and re flashing seems to happen randomly, but after it does it wont stop and persists even when not playing a game.

I tend to use the xmb style menu with the scrolling playstation style menu and you can see the stutter happen within that ribbon really easily. 

Usually happens within a day or so of flashing, I though there was something wrong with my device but it acts normal if I wipe and reinstall.

Factory reset doesn't fix and clearing retroarch defaults doesn't fix issue. Only a wipe and reinstall will solve it. 

Just trying to report this if its a bug, sorry I posted this under a different account than intended I attempted to delete where I could fix that but it wouldnt let me.

**Comment by Sundownersport** [comment]
Is your WiFi on?
Have you updated the firmware?
What release version are you using?
What kind of computer operating system do you use to install spruce?

**Comment by JohnShatto** [comment]
Yeah wifi is on

I thought so but I will try that right now and see if the issue disappears. 

This seems to happen when I attempt to play the A30 away from home so its not connected when this happens but wifi is still on.
latest version but it has done this for a while I just assumed at first that this device was just a piece of junk but it worked great when I update releases and while at home. 

Windows 10 mainly tried on Ubuntu once. 
use sd formatter to clear the card then rufus to format sd as fat32 non bootable.

**Comment by JohnShatto** [comment]
ohh god why does the firmware update change how retroarch saves its game saves, you can no longer see the root of the SD and have to pick a folder inside the \mnt\SDCARD\RetroArch\.retroarch folder instead of the \mnt\SDCARD\save folder on the root of the card. 
Guess I was on the older firmware. If I can get my saves synced with syncthing I will test a game to see if the issue is gone.

**Comment by Sundownersport** [comment]
So you updated your firmware now? What version did you use?

what spruce release version are you on?

**Comment by JohnShatto** [comment]
I used the firmware listed here https://github.com/spruceUI/spruceOS/wiki/Updating-Firmware-and-Unbricking-an-A30
says 20240713100458 now

current release. 2.2.2
Strange how you cant map any folder beyond the  Retroarch\ .retorarch folder

Just wont let you go any higher so you can not use the default save folder now. 
But I worked with this limit and got my syncthing setup working. 

Original stutter issue seems to be gone for now.

**Comment by spruceUI** [comment]
i am not sure what you have done with your install but you should try following the update procedure to reset all the settings to the spruce standard. 

Dont reset Retroarch settings..... it breaks things. Stop messing with Retroarch unless you really need to, its clunky and hard to understand. 

Retroarch saves and in game saves (like pokemon for example) save to the Saves folder on the root of the SD.

In Game Menu (with the Home button) saves live in the Roms folders.

**Comment by JohnShatto** [comment]
Okay, wiping it now and will reinstall with a fresh download and see if retroarch save location defaults as expected. No issues with freezing since firmware upgrade so that's nice. 

That seemed to fix the retroarch settings, saves are now going where intended.

I am sorry, I prefer to adjust things in Retroarch, its mainly personal preference but I have a few dozen of these handhelds different manufactures but almost all run 
Retroarch in the back-end and I am well versed in the config settings and whatnot. I try to make them all control the same, modify hotkeys, and control settings, etc.  

That being said I can see how resetting to default settings might not always work as intended and could cause corruption.  Must have custom settings for spuce that get wiped if you hit reset to defaults. That is probably what reset the save location to the .retroarch/saves folder. 

Yup that is how it should work and does now after wiping and reinstalling.

Are you talking about the simple menu via menu button save and load states, I didn't notice a save button in that menu, considered disabling it since I thought it might be causing issues. Ill mess with that a bit. 


To conclude. If you have stuttering issues upgrade firmware.
The firmware doesnt just impact wifi issues as described.
Now the stuttering was probably caused by non updated firmware and a syncthing setup that was connected to wifi then put device to sleep and resumed when not connected to that wifi.
After that the console stuttered even in retroarch menu without a game playing.
Only thing to temp fix stuttering was a wipe and reinstall. 
Perm fix for stuttering was a firmware upgrade wipe and reinstall. 

Thanks for the great work making the A30 a good micro console. 
I appreciate the support. I hope this helps anyone else who has the stuttering issue. I couldn't find anything about it online.

**Comment by spruceUI** [comment]
if you prefer Retroarch over the In-Game Menu (the simple menu you referenced) you can use "Retroarch Expert Mode", simply enable it in the App section. 

This allows for more custom hotkeys and it does not have the In-Game Menu.
