### ISSUE TITLE
Sound extremely quiet

### ISSUE THREAD

**Issue by manzaloros** [spruceUI/spruceOS#49]
Latest spruce version
Latest a30 firmware

The loudest volume setting (20/20) is extremely quiet, coming from the external speakers (not headphones). I have tried the audio fix on and off. Before the latest Spruce update the volume was at a normal level.

**Comment by manzaloros** [comment]
> boot without sd card

The sound is at a normal level (the expected volume) without an SD card.

I have been using this SD card (Sandisk Ultra) since I first installed Spruce, and had normal levels before the most recent update.

**Comment by Sundownersport** [comment]
Try a fresh install of spruce. I think this is sd card corruption
