### ISSUE TITLE
[Bug] Wiki link directs to old tenlevels repo instead of spruce

### ISSUE THREAD

**Issue by robonxt** [spruceUI/spruceOS#72]
In the [Adding Games!](https://github.com/spruceUI/spruceOS/wiki/Adding-Games!) Wiki page, the link to the `Arcade and MAME Explained!` is still pointing to
[https://github.com/tenlevels/spruce/wiki/Arcade-and-MAME-Explained!](https://github.com/tenlevels/spruce/wiki/Arcade-and-MAME-Explained!) 
instead of 
[https://github.com/spruceUI/spruceOS/wiki/Arcade-and-Mame-Explained!](https://github.com/spruceUI/spruceOS/wiki/Arcade-and-Mame-Explained!)

**Comment by spruceUI** [comment]
lol nice catch!

**Comment by spruceUI** [comment]
Fixed it!
