### ISSUE TITLE
Mupen64 default keymap is incorrect

### ISSUE THREAD

**Issue by mbehfar** [spruceUI/spruceOS#75]
In the default N64 keymap, abxy are mapped to the wrong buttons and the dpad is mapped to to a digital input that the a30 doesnt use.

Here is a modified n64.rmp file to correct these issues:
The path to change the file is RetroArch > .retroarch > config > remaps > Mupen64Plus GLES2

------------------------------

input_libretro_device_p1 = "1"
input_libretro_device_p2 = "1"
input_libretro_device_p3 = "1"
input_libretro_device_p4 = "1"
input_libretro_device_p5 = "1"
input_player1_analog_dpad_mode = "1"
input_player1_btn_a = "0"
input_player1_btn_b = "1"
input_player1_btn_down = "22"
input_player1_btn_left = "21"
input_player1_btn_right = "20"
input_player1_btn_up = "23"
input_player1_btn_y = "8"
input_player1_stk_r_x+ = "-1"
input_player1_stk_r_x- = "-1"
input_player1_stk_r_y+ = "-1"
input_player1_stk_r_y- = "-1"
input_player2_analog_dpad_mode = "0"
input_player3_analog_dpad_mode = "0"
input_player4_analog_dpad_mode = "0"
input_player5_analog_dpad_mode = "0"
input_remap_port_p1 = "0"
input_remap_port_p2 = "1"
input_remap_port_p3 = "2"
input_remap_port_p4 = "3"
input_remap_port_p5 = "4"

**Comment by Sundownersport** [comment]
I’ll take a look at this later!

a and b are mapped to b and x to mimic the layout of an n64 controller. I know it’s odd having the a30 b button be the n64 a button

**Comment by mbehfar** [comment]
Gotcha! Maybe showing my age a bit with the button layout haha.

Either way the directionals still need to be remapped to work. Tested on Ocarina of Time with the item buttons.

Thanks for the quick response!

**Comment by Sundownersport** [comment]
Item buttons like with equipped items? So the C buttons?
