### ISSUE TITLE
Expert app switch not working

### ISSUE THREAD

**Issue by CrossToBear** [spruceUI/spruceOS#79]
Expert app switch not working on 2.3 version. I'm stuck with no apps. Do you know the fix?

**Comment by Sundownersport** [comment]
Sounds like your problem install went wrong.

does your SD card have a “.tmp_update” folder?

**Comment by CrossToBear** [comment]
> Sounds like your problem install went wrong.
> 
> does your SD card have a “.tmp_update” folder?

Damnit I deleted it. Now what?

**Comment by CrossToBear** [comment]
Ok, yes I did deleted it, the instructions where to keep only config folder from hidden folders. Now what's the solution?
  

  

  
  
Kind regards
  
Dr. Dimitri Lashkhi
  

  

        
  
  
>

**Comment by CrossToBear** [comment]
Ok I fixed it. Thank brother!
