### ISSUE TITLE
How come the source code isn't baked into the repo?

### ISSUE THREAD

**Issue by BaseInfinity** [spruceUI/spruceOS#8]
I know the source code is baked in the releases, but how come it's not baked into the github repo?

**Comment by spruceUI** [comment]
because basically I am lazy and don't want to have to go through and update it constantly with each new releases. Also I am new to Github and its kind of confusing for me.

Its just sort of how spruce has been since the beginning and I am not one to change that without an excellent reason.

**Comment by BaseInfinity** [comment]
Gotcha okay,  (this is Basecase_ from Reddit), Let me know if you ever want me to submit a pull that turns this into a repo with committed files and want a quick rundown of Git/Github (it's def a learning curve but worth it I think)

One positive is it makes it easier to collab with other people who know Git as well but that's all I can think of for now

Thanks again for the work put in here!

**Comment by spruceUI** [comment]
thanks! im not super interested in doing that honestly. I'm trying to keep the github as trimmed as possible and dont really want to mess with it.

i have a private page set up for the dev team to collab on and invite people to join it if they reach out with help

**Comment by BaseInfinity** [comment]
Sounds good! I'll reach out if I add anything significant, thanks!
