### ISSUE TITLE
Page up and down game selection

### ISSUE THREAD

**Issue by novamaru** [spruceUI/spruceOS#89]
I really love the MinUInspired themes, but MinUI also has one particularly useful feature that might be worth adopting for Spruce, which is the ability to use the left and right D-pad to page up and down the game selection list. So up and down moves by one row, and left and right moves by one page (i.e., 6 rows). This makes for a fast and intuitive way to navigate a large list of games. Currently it seems left D-pad does nothing and right D-pad brings up the game info, while the A and Y buttons both launch the selected game. So perhaps there could be an option to have Y bring up game info instead, and then left and right directions are both free for page up/down.

**Comment by spruceUI** [comment]
This is just how MainUI is and we cannot change it.
