### ISSUE TITLE
Feature: Add ability to switch Cores for GB and GBC

### ISSUE THREAD

**Issue by BaseInfinity** [spruceUI/spruceOS#9]
Gambatte has issues with syncing states across devices for some reason for GB and GBC.

This allows the user to choose between mGBA and Gambatte for their core for either GB or GBC.

mGBA has better support for cross device state saves.

Changes for GB:
https://github.com/BaseInfinity/spruce-dev-environment/commit/282c2a073812701dc72da3d454686749c69e4520

Changes for GBC:
https://github.com/BaseInfinity/spruce-dev-environment/commit/608974ce30ba0091133e6c205ad3f155e5861613

**Comment by spruceUI** [comment]
Awesome! Ill add those to 2.1 because, why not?
