### ISSUE TITLE
Optionally disable global R2 fast forward

### ISSUE THREAD

**Issue by novamaru** [spruceUI/spruceOS#90]
I play a lot of Street Fighter games and I would like a way to disable R2 for the fast-forward feature. In some cases I want to use R2 just for regular game controls (as an easier-to-reach alternative to L, for example). But I also find that it's generally far too easy to hit R2 by accident during frantic game play, inadvertently triggering fast-forward when it's not desired. So it would be great it there were a Spruce menu option to toggle the global setting for R2 a fast-forward.

In the meantime it would also be nice to know if there is a some other way to disable this using the Retroarch settings that we are not supposed to touch.

**Comment by spruceUI** [comment]
in Retroarch FF is in the Hotkeys section. Change this to Nul and save your override.
