### ISSUE TITLE
Firmware Update link not working

### ISSUE THREAD

**Issue by PailosNicolas** [spruceUI/spruceOS#93]
I tried downloading the firmware update from the wiki and the link does not start download and it does not redirects to somewhere else.

**Comment by robertacurtis** [comment]
I am currently trying to download and it fails to get past 70Mb.

**Comment by ryanmsartor** [comment]
Hey y'all, you can also find the latest firmware inside the spruce/FIRMWARE UPDATE folder in the latest spruce release. Follow the update instructions on the wiki using the file you find there.

**Comment by PailosNicolas** [comment]
> Hey y'all, you can also find the latest firmware inside the spruce/FIRMWARE UPDATE folder in the latest spruce release. Follow the update instructions on the wiki using the file you find there.

Thanks I didn't know.
